# Generated by Django 4.2.5 on 2024-05-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(default='exit', upload_to='report_images/'),
            preserve_default=False,
        ),
    ]
