# Generated by Django 4.2.5 on 2024-05-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='disaster_type',
            field=models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('hurricane', 'Hurricane'), ('wildfire', 'Wildfire'), ('tornado', 'Tornado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
